# Copyright (c) 2020-2022 Pcap Project
# SPDX-License-Identifier: MIT OR Apache-2.0

version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "22:00"
    open-pull-requests-limit: 10