
To build the source you will need to install:

- Libpcap (Unix based system) or Npcap (for Windows)
- JDK 8 and JDK 14 (with Panama EA)

Pcap uses Maven for most build-related activities, and you
should be able to get off the ground quite quickly by cloning the
project and typing:

[indent=0]
----
$ export JAVA_HOME_8=<PATH TO JDK 8>
$ export JAVA_HOME_14=<PATH TO JDK 14 (with Panama EA)>
$ exprrt JAVA_HOME=${JAVA_HOME_14}
$ ./mvnw -B -t .mvn/toolchains.xml clean package jacoco:report-aggregate -Pcoverage -Plegacy-support -Pformat
----

NOTE: Don't forget to install JDK 8 for activating `legacy-support` profile and set `JAVA_HOME_8` as environment
variable to the installation path. JDK 14 (with panama ea) is required for building `api` module and you need to
set `JAVA_HOME_14` as environment variable also to the installation path. Your `JAVA_HOME` path should be same
as `JAVA_HOME_14` and when executing above command you need to specify the `toolchains.xml` configuration by adding
`MVN_OPTS` like `-t ./mvn/toolchains.xml`.

NOTE: You can also install Maven (>=3.5.4) yourself and run the `mvn` command
instead of `./mvnw`.

For hints on how to build the project look in `.github/workflows/developement.yml` if there
is one. There should be a "script" and maybe "maven package" command.
